---
- name: Check if VM is running on AWS
  hosts: 10.1.0.61
  connection: ssh
  gather_facts: no

  vars:
    aws_region: us-east-1
    aws_keypair_name: lc-aaponaws-mar2023
    instance_id: i-0f0973f015c2186a8

  tasks:
    - name: Gather facts for EC2 instance
      ec2_remote_facts:
        region: "{{ region }}"
        filters:
          "instance-id": "{{ instance_id }}"
      register: ec2_facts

    - name: Print instance state
      debug:
        var: ec2_facts.instances[0].state.name
