---
- name: Update packages on remote host
  hosts: 10.1.0.61
  remote_user: ec2-user
  become: true
  gather_facts: false
  connection: ssh

  tasks:
    - name: Run yum update
      yum:
        name: '*'
        state: latest
      become: true
