---
- name: Update packages on remote host
  hosts: 10.1.0.61
  become: true
  remote_user: ec2-user
  gather_facts: false
  

  tasks:
    - name: Run yum update
      yum:
        name: '*'
        state: latest
      become: true
