---
- name: JBoss EAP installation
  hosts: jboss-host
  become: true
  tasks:
    - name: Download JBoss EAP binaries
      get_url:
        url: "https://drive.google.com/file/d/1E3rVr7Q23T6D96g8HayfNsCXoMs6pk_Y/view?usp=share_link"
        url_username: lseet@redhat.com
        url_password: !S33tLengShanice
        dest: /opt

    - name: Unzip the downloaded ZIP file
      unarchive:
        src: /opt/jboss-eap-7.4.zip
        dest: /opt
        remote_arc: yes

    - name: Create JBoss EAP Group
      group:
        name: jboss-group
        system: yes
        state: present
 
    - name: Create JBoss EAP user
      user:
        name: jboss-user
        group: jboss-group
        password: pa$$w0rd
        home: /opt/jboss-eap-7.4
        shell: "/bin/bash"

   - name: Change owner & group of JBoss EAP directory
     file:
       path: /opt/jboss-eap-7.4
       owner: jboss-user
       group: jboss-group
       recurse: yes

   - name: Edit JBoss EAP configuration file
     lineinfile:
       state: present
       path: /opt/jboss-eap-7.4/bin/init.d/jboss-eap.conf
       regexp: "{{ item.regexp }}"
       line: "{{ item.line }}"
     with_items:
       - {regexp: "^# JAVA_HOME=", line: 'JAVA_HOME="/opt/jdk-18.0.2.1"'}
       - {regexp: "^# JBOSS_HOME=", line: 'JBOSS_HOME="/opt/jboss-eap-7.4"'}
       - {regexp: "^# JBOSS_USER=", line: 'JBOSS_USER=jboss-user'}

   - name: Update /etc/profile with JBOSS_HOME variable
     lineinfile:
       path: /etc/profile
       state: present
       line: "{{ item }}"
     with_items:
       - 'export JBOSS_HOME="/opt/jboss-eap-7.4"'
       - 'export PATH=$PATH:$JBOSS_HOME/bin'

   - name: Configure JBoss EAP as a service
     command:
       chdir: /opt/jboss-eap-7.4
       cmd: "{{item }}"
     with_items:
       - cp /opt/jboss-eap-7.4/bin/init.d/jboss-eap.conf /etc/default/
       - cp /opt/jboss-eap-7.4/bin/init.d/jboss-eap-rhel.sh /etc/init.d/
       - restorecon /etc/init.d/jboss-eap-rhel.sh
       - chkconfig --add jboss-eap-rhel.sh 

   - name: Start JBoss EAP Service
     service:
       name: jboss-eap-rhel
       state: started
       enabled: yes
