---
- name: Pull Windows patches from SCCM
  hosts: windows_servers
  gather_facts: no
  vars:
    sccm_server: "sccm_server_name"
    sccm_site_code: "sccm_site_code"
    sccm_username: "sccm_username"
    sccm_password: "sccm_password"
    wsus_server: "wsus_server_name"
    wsus_port: "wsus_port_number"
    patch_category: "Critical Updates,Security Updates,Update Rollups"
  tasks:
    - name: Get list of available patches
      win_updates:
        category_names: "{{ patch_category }}"
        state: search
        update_server: "{{ wsus_server }}"
        update_port: "{{ wsus_port }}"
        register: available_patches

    - name: Install available patches
      win_updates:
        category_names: "{{ patch_category }}"
        state: installed
        update_server: "{{ wsus_server }}"
        update_port: "{{ wsus_port }}"
        reboot: yes
        reboot_timeout: 3600
        register: installed_patches

    - name: Get list of missing patches
      win_updates:
        category_names: "{{ patch_category }}"
        state: installed
        update_server: "{{ wsus_server }}"
        update_port: "{{ wsus_port }}"
        register: missing_patches

    - name: Send missing patches to SCCM
      win_sccm:
        site_code: "{{ sccm_site_code }}"
        server: "{{ sccm_server }}"
        username: "{{ sccm_username }}"
        password: "{{ sccm_password }}"
        action: approve
        category_names: "{{ patch_category }}"
        product_names: "Windows 10"
        status: required
        criticality: critical
        update_names: "{{ missing_patches.updates | map(attribute='hotfix_id') | list }}"