---
- name: Update client OS
  hosts: client
  become: yes

  tasks:
  - name: Update package cache
    dnf:
      update_cache: yes
    when: ansible_pkg_mgr == 'dnf'

  - name: Update all packages
    dnf:
      name: '*'
      state: latest
    when: ansible_pkg_mgr == 'dnf'

  - name: Update package cache
    yum:
      update_cache: yes
    when: ansible_pkg_mgr == 'yum'

  - name: Update all packages
    yum:
      name: '*'
      state: latest
    when: ansible_pkg_mgr == 'yum'


