---
- name: Update packages on remote host
  hosts: localhost
  become: true
  gather_facts: false
  
  

  tasks:
    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: '*'
        state: latest
      become: true



