---
- name: Update packages on remote host
  hosts: all
  become: true
  gather_facts: false
  
  

  tasks:
    - name: Run yum update
      yum:
        name: '*'
        state: latest
      become: true
